const menu = [
  {
    id: 1,
    title: 'empanadas',
    category: 'entradas',
    price: 200.00,
    img: './images/item-1.jpeg',
    desc: `Empanadas de cordero, carne y/o queso acompañadas con llajua (precio por unidad).`,
  },
  {
    id: 2,
    title: 'brusquettas',
    category: 'entradas',
    price: 600.00,
    img: './images/item-2.jpeg',
    desc: `Pan de campo, queso crema, tomates confitados (con 2 salsas, berenjena ahumada, dulce de locoto).`,
  },
  {
    id: 3,
    title: 'crema de calabaza',
    category: 'sopas',
    price: 1000.00,
    img: './images/item-3.jpeg',
    desc: `Verduras de la quebrada, calabaza, batata caramelizada y láminas de parmesano.`,
  },
  {
    id: 4,
    title: 'crema de choclo c/ charqui',
    category: 'sopas',
    price: 1100.00,
    img: './images/item-4.jpeg',
    desc: `Verduras de la quebrada, maíz molido y charqui.`,
  },
  {
    id: 5,
    title: 'mix de verdes con verduras',
    category: 'ensaladas',
    price: 1200.00,
    img: './images/item-5.jpeg',
    desc: `Hojas verdes, tomates confitados y verduras horneadas con dip de zanahoria.`,
  },
  {
    id: 6,
    title: 'ensalada de rúcula y quinoa',
    category: 'ensaladas',
    price: 1300.00,
    img: './images/item-6.jpeg',
    desc: `Rúcula, quinoa, cebolla morada, zanahoria, con dip de yogur.`,
  },
  {
    id: 7,
    title: 'cazuela de quinoa',
    category: 'principales',
    price: 1700.00,
    img: './images/item-7.jpeg',
    desc: `Cazuela de quinoa, verduras y zanahorias glaseadas.`,
  },
  {
    id: 8,
    title: 'tallarines cintas',
    category: 'principales',
    price: 1100.00,
    img: './images/item-8.jpeg',
    desc: `Adicionales: salsa de hongos $600, tuco $550, crema $450 y salsa mixta $500.`,
  },
  {
    id: 9,
    title: 'estofado de cordero',
    category: 'principales',
    price: 2300.00,
    img: './images/item-9.jpeg',
    desc: `Estofado de cordero con cerveza negra y papas gratinadas.`,
  },
  {
    id: 10,
    title: 'arepas rellenas',
    category: 'principales',
    price: 1900.00,
    img: './images/item-10.jpeg',
    desc: `Sobre crema de semillas de girasol (Pollo con variedad de pimientos / Verduras al wok y hummus de berenjena).`,
  },
  {
    id: 11,
    title: 'tallarines cinta',
    category: 'menú niños',
    price: 800.00,
    img: './images/item-11.jpeg',
    desc: `Tallarines cinta con salsa fileto, crema, oliva y queso.`,
  },
  {
    id: 12,
    title: 'pizzeta',
    category: 'menú niños',
    price: 900.00,
    img: './images/item-12.jpeg',
    desc: `Pizzetas con salsa de tomates frescos y muzarella.`,
  },
  {
    id: 13,
    title: 'duraznos asados',
    category: 'postres',
    price: 700.00,
    img: './images/item-13.jpeg',
    desc: `Duraznos asados sobre base de crema de anchi.`,
  },
  {
    id: 14,
    title: 'flan casero',
    category: 'postres',
    price: 700.00,
    img: './images/item-14.jpeg',
    desc: `Flan casero con caramelo, opcional dulce de leche y/o crema.`,
  },
  {
    id: 15,
    title: 'brownie con helado',
    category: 'postres',
    price: 850.00,
    img: './images/item-15.jpeg',
    desc: `Brownie con helado de crema americana y coulis de frutos rojos.`,
  },
  {
    id: 16,
    title: 'quesillo con dulce de cayote',
    category: 'postres',
    price: 750.00,
    img: './images/item-16.jpeg',
    desc: `Quesillo con dulce de cayote, nuez y miel de caña.`,
  },
];
export default menu;
